[project]
name = "repo-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "pyqt6>=6.9.0",
    "python-docx>=1.1.2",
]
